import './globals.css'
import React from "react";
import Navbar from './components/ui/navbar'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cn } from '@/lib/utils'
import { MainStoreProdiver } from '@/lib/providers/main-store'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={cn(inter.className, 'bg-gray-50')}>
				<MainStoreProdiver>
					<Navbar />
					<div className='w-11/12 sm:container mx-auto py-5'>{children}</div>
				</MainStoreProdiver>
			</body>
		</html>
	)
}
